name: 'Agentic Testing Action'

description: 'Run tests and report results'
author: 'TestZeus'

inputs:
  email:
    description: 'TestZeus login email'
    required: true
  password:
    description: 'TestZeus login password'
    required: true
  name:
    description: 'Name for the test run group'
    required: false
    default: 'Smoke action suite'
  execution_mode:
    description: 'Execution mode for the test run (lenient or strict)'
    required: false
    default: 'lenient'
  filename:
    description: 'Filename for the CTRF report output'
    required: false
    default: 'ctrf-report.json'
  notification_channels:
    description: 'Notification channels ids for the test run eg: "1234567890,1234567891"'
    required: false
    default: ''
  
runs:
  using: 'composite'
  steps:
    - name: Install dependencies  
      shell: bash
      run: |
        pip install --upgrade testzeus-cli jq python-dateutil

    - name: Login to TestZeus
      shell: bash
      run: |
        echo "🔐 Logging into TestZeus..."
        LOGIN_OUTPUT=$(testzeus login --email "${{ inputs.email }}" --password "${{ inputs.password }}" 2>&1)

        if echo "$LOGIN_OUTPUT" | grep -q "Login failed"; then
          echo "❌ Login failed: aborting action."
          exit 1
        fi

        echo "✅ Successfully logged into TestZeus."

    - name: Generate Test Report
      shell: bash
      run: |
        echo "Creating test..."
        chmod +x "${{ github.action_path }}/scripts/create_test_report.sh"
        export TEST_RUN_NAME="${{ inputs.name }}"
        export EXECUTION_MODE="${{ inputs.execution_mode }}"
        export REPORT_FILENAME="${{ inputs.filename }}"
        export NOTIFICATION_CHANNELS="${{ inputs.notification_channels }}"
        "${{ github.action_path }}/scripts/create_test_report.sh"
