name: 'Agentic Testing Action'

description: 'Run tests and report results'
author: 'TestZeus'

inputs:
  email:
    description: 'TestZeus login email'
    required: true
  password:
    description: 'TestZeus login password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies  
      shell: bash
      run: |
        pip install --upgrade testzeus-cli jq

    - name: Login to TestZeus
      shell: bash
      run: |
        echo "🔐 Logging into TestZeus..."
        LOGIN_OUTPUT=$(poetry run testzeus login --email "${{ inputs.email }}" --password "${{ inputs.password }}" 2>&1)

        if echo "$LOGIN_OUTPUT" | grep -q "Login failed"; then
          echo "❌ Login failed: aborting action."
          exit 1
        fi

        echo "✅ Successfully logged into TestZeus."

    - name: Generate Test Report
      shell: bash
      run: |
        echo "Creating test..."
        chmod +x "${{ github.action_path }}/scripts/create_test_report.sh"
        "${{ github.action_path }}/scripts/create_test_report.sh"
